### PR TITLE
Indicate test results via a button in reading mode

### PR DESCRIPTION
**Pull request by Elchi3**
This adds a ToggleButton to the add-on.
In reading mode, an XHR request is made to the raw
version of a page. The button then shows the total
number of errors and warnings from testing against
the raw version. Clicking the button shows the
detailed results in the sidebar as usual.
When editing, the button is disabled, but will
show the result number as visual help.

This aims to fix issue #36.

### CODE REVIEW

**Comment by Elchi3** [comment]
Open points:
- I forgot to translate the label of the button.
- There is `innerHTML` used and I haven't thought about how to avoid it yet.

@SebastianZ If you have time, I would appreciate feedback/review on this, but -as always- there is no hurry!

**Comment by SebastianZ** [comment]
Very cool approach! I really like that toolbar button.

Some issues I see:
1. The button is disabled most of the time, though it should only be disabled when you are not at an MDN page. (I didn't investigate why yet.)
2. The number of errors and warnings is only shown after the sidebar was opened at least once. (Though sometimes it works as expected. Didn't find a pattern yet.)
3. I suspect some MDN authors don't know what a linter is. So I suggest to rename the button tooltip. E.g. simply use the extension's name 'MDN documentation tester'.
4. I think it would be better to just set a CSS filter instead of having a separate icon for the disabled state of the button.

I just reviewed the functionality and only had a quick look at the code so far. I still need to do a thorough code review.

> Open points:
> - I forgot to translate the label of the button.

I'm happy to do that once the points above are fixed.

> - There is `innerHTML` used and I haven't thought about how to avoid it yet.

Hmm, maybe [`DOMParser`](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) can help here?

Sebastian

**Comment by SebastianZ** [comment]
Another point: This PR contains three logical changes:
1. It adds a toolbar button to toggle the sidebar.
2. It adds functionality to display the sidebar also in reading mode.
3. It adds an error indication to the button.

So, the changes may have been split up accordingly. Though, I guess now it's a bit late for that. :-)

Sebastian

**Comment by Elchi3** [comment]
I rebased this PR and I hope I have addressed most of the code comments. 

Some of the functional issues still need more investigation and I don't know if they should block merging.

> 1. The button is disabled most of the time, though it should only be disabled when you are not at an MDN page. (I didn't investigate why yet.)

Sometimes this seems to work fine, sometimes not. Need to observe more.

> 1. The number of errors and warnings is only shown after the sidebar was opened at least once. (Though sometimes it works as expected. Didn't find a pattern yet.)

Same here.

> 1. I think it would be better to just set a CSS filter instead of having a separate icon for the disabled state of the button.

I have not researched how to do this with CSS. If you know how, please let me know.

**Comment by SebastianZ** [comment]
> Some of the functional issues still need more investigation and I don't know if they should block merging.
> 
> > 1. The button is disabled most of the time, though it should only be disabled when you are not at an MDN page. (I didn't investigate why yet.)
> 
> Sometimes this seems to work fine, sometimes not. Need to observe more.

This definitely needs to be fixed before merging.

> > 1. The number of errors and warnings is only shown after the sidebar was opened at least once. (Though sometimes it works as expected. Didn't find a pattern yet.)
> 
> Same here.

This also needs to be fixed.

> > 1. I think it would be better to just set a CSS filter instead of having a separate icon for the disabled state of the button.
> 
> I have not researched how to do this with CSS. If you know how, please let me know.

It's somewhat harder to do. You need to create a CSS file with a CSS rule containing the filter for the icon, add a manifest file to make it accessible via a URL and then add it to the browser's chrome context via some JavaScript on initialization.
I skimmed through the Add-on SDK and it might be possible to add the CSS using the ['stylesheet/utils' API `loadSheet()`](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/stylesheet_utils), though I didn't try it out yet.

You may try it, though I think it's ok to keep the disabled icon for now and investigate that in a separate issue.

I'll have a look if I can find out what's causing the two issues above.

Sebastian

**Comment by Elchi3** [comment]
Updated again to let the tests run directly after the XHR is done.

I am not going to work on the CSS filter for the icon.

**Comment by Elchi3** [comment]
Rebased again.

**Comment by SebastianZ** [comment]
I've fixed the toolbar button state. It was set incorrectly when opening the sidebar and switching between tabs.

After fixing it, I saw a few more issues:
1. When you're editing an article and click the toolbar button twice (to close and open the sidebar), the _Run tests_ button and the interval for running the tests don't work anymore.
2. If the sidebar is closed, the toolbar button is still checked.
3. Unchecking the toolbar button disposes the sidebar. It's probably be better if it only got hidden, as it works together with hiding the sidebar via the X within the sidebar and may allow to show the test results immediately after opening it. (As the tests were already run to display the number of errors in the button badge, those results should be reused instead of running the test suite again.)
4. With the point above fixed, we won't need the _Run tests_ button anymore in reading mode, as the tests would only be run once. So it could be removed.

The last three points may be tackled in follow-ups, though the first one needs to be fixed before merging the PR. Please have a look at that.

Sebastian

**Comment by Elchi3** [comment]
I rewrote this again. Was quite unhappy with the code and how it worked.

> I am not going to work on the CSS filter for the icon.

There is https://bugzilla.mozilla.org/show_bug.cgi?id=1167559 btw.

The button state is really confusing, but I hope it is correct now. There is something about it in the docs: https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/ui_button_toggle#Updating_checked

**Comment by SebastianZ** [comment]
The code looks much cleaner now, but you also broke the button state again.
Thanks for referring to the related bug! I agree that the state behavior is confusing.
We should still fix it as far as we can, though.

Sebastian

**Comment by Elchi3** [comment]
Did you restart the window? The button state was weird for me at some point, but I think that was because it messed with the state within the window and so I restarted Firefox. If it is not that, I am curious to hear what you mean by "broken". :-)

**Comment by SebastianZ** [comment]
Yes, I am always restarting the browser after making changes.
"broken" means that the button is disabled once the tests ran while the sidebar is open.

Sebastian

**Comment by Elchi3** [comment]
I was testing in Release, but can reproduce in Nightly :)

**Comment by SebastianZ** [comment]
> I was testing in Release, but can reproduce in Nightly :)

I see. Sounds like a Firefox regression. I'll investigate that.

Sebastian

**Comment by SebastianZ** [comment]
Strange, now I see another behavior, independently of whether I run on Release or Nightly.
The button works as expected but the sidebar is broken sometimes.
Tested on https://developer.mozilla.org/en-US/docs/Web/CSS/margin running `jpm run -b "C:\Program Files\Mozilla Nightly\firefox.exe"`:

**Reading mode:**
1. sidebar closed :white_check_mark:, button active :white_check_mark:
2. error badge updates and shows 9 errors :white_check_mark:
3. clicking toolbar button opens sidebar :white_check_mark:
4. clicking _Run tests_ runs the tests :white_check_mark:

**Editing mode:**
1. sidebar opened :white_check_mark:, button active and pressed :white_check_mark:
2. clicking _Run tests_ does **not** run tests :x:
3. clicking toolbar button closes sidebar :white_check_mark:
4. clicking toolbar button again opens sidebar, matches displayed in sidebar, button active, errors badge displays 9 errors :white_check_mark:

So, that looks much better than yesterday. Did you commit something else?
The only point that needs to be fixed now seems to be that you can't run the tests when entering the editing mode.

One small issue, when you are at the login page with a redirect like https://developer.mozilla.org/en-US/users/signin?next=/en-US/docs/Web/API/MediaRecorder/start%24edit, the toolbar button is active and shows errors, while it should be deactivated.

Sebastian

**Comment by Elchi3** [comment]
Thanks for the detailed debugging!
- For some reason, the button state now also works in both Release and Nightly for me. I have not committed anything in that regard. /me shrugs
- "Can't run the tests when entering the editing mode". I can reproduce sometimes, but sometimes not. I think what happens is that the `self.port.on("editing"` function is called early when the editing iframe element is not there yet. It works if the broken edit tab is loaded, you switch to another tab and back to the loaded edit tab, because then `self.port.on("editing"` is called again.  I experimented a bit, but I haven't found a solution yet.

I added a commit:
- to fix the login case.
- to use `includes()` instead of `indexOf()`

> Having a fixed list of areas looks a bit bad to me. It would be better to handle this more generally

I agree, but I think this can be a follow-up.

**Comment by SebastianZ** [comment]
If you don't have time yet to look into this, I'd say to do the release now and defer this to the next version.

Sebastian

**Comment by Elchi3** [comment]
> If you don't have time yet to look into this, I'd say to do the release now and defer this to the next version.

I am sorry, and yes agreed. I just released.

**Comment by SebastianZ** [comment]
Great, thanks!
Note that the [link on AMO](https://addons.mozilla.org/en-US/firefox/addon/mdn-documentation-tester/versions/) to the release notes is not interpreted correctly.

Sebastian

**Comment by Elchi3** [comment]
Closing. We might re-use some ideas of this in the future, but the PR as-is is unusable.

**Pull request closed without merging**
