### PR TITLE
Issue 17: Added word count and reading time estimation

### PR DESCRIPTION
**Pull request by SebastianZ**
This new approach uses the same regular expression as the previous one in the [issue-17 branch](https://github.com/Elchi3/mdn-doc-tests/tree/issue-17), though it is much faster, as it just works on the text content and doesn't need to remove the HTML tags first.

It outputs the word count and read time estimation as info message and adds a warning in case the text is longer than 1000 words.

Sebastian

### CODE REVIEW

**Comment by Elchi3** [comment]
This is really well done. Code looks good to me and it is fast :) 

I think 1000 is too strict, though. I would have put 2500. Thoughts? Should this be a preference?

**Comment by SebastianZ** [comment]
> I think 1000 is too strict, though. I would have put 2500. Thoughts? Should this be a preference?

2.500 is a bit too much, I think. Let's say 2.000. And I'll make it a preference, so people can change it as they like.

Sebastian

**Comment by SebastianZ** [comment]
> > I think 1000 is too strict, though. I would have put 2500. Thoughts? Should this be a preference?
> 
> 2.500 is a bit too much, I think. Let's say 2.000. And I'll make it a preference, so people can change it as they like.

I've turned the constant into the preference `longArticleWordCountThreshold` now and assigned it the value 2.000. Note that the preference is hidden from the Add-ons Manager, because I think people should normally not change it.

Sebastian

**Comment by Elchi3** [comment]
This is really cool. Thanks again for picking this up!

**Pull request merged**
