### PR TITLE
Issue 186: Broaden jsref-with-params test

### PR DESCRIPTION
**Pull request by SebastianZ**
Broadened the test for {{JSRef}} params to also check {{csssyntax}}, {{cssinfo}} and {{svginfo}} and improved the output error messages.

Sebastian

### CODE REVIEW

**Comment by Elchi3** [comment]
I didn't notice the rule "The parameters of the %s macro are unnecessary, because they will be fetched from the slug, so they should be removed." when reading the code at first. Is this testable? 

I start feel that tests should have a comment on top explaining what their purpose is or the cases they are dealing with. I mean yes, you can figure out the rules from the code and the tests, but this took me a minute or two.

**Comment by Elchi3** [comment]
This works as expected otherwise. Test for the slug case would be ideal, but feel free to merge without. r+

**Comment by SebastianZ** [comment]
> I didn't notice the rule "The parameters of the %s macro are unnecessary, because they will be fetched from the slug, so they should be removed." when reading the code at first. Is this testable?

We'd need to load some real page to check that. Or can you think of a way to fake the URL?

> I start feel that tests should have a comment on top explaining what their purpose is or the cases they are dealing with. I mean yes, you can figure out the rules from the code and the tests, but this took me a minute or two.

Yes, we should add some comments. File an issue?

Sebastian

**Comment by Elchi3** [comment]
> We'd need to load some real page to check that. Or can you think of a way to fake the URL?

No idea. Let's ignore this for now then.

> Yes, we should add some comments. File an issue?

Filed issue #211.

**Pull request merged**
