### PR TITLE
Added test for HTTP links (issue #16)

### PR DESCRIPTION
**Pull request by SebastianZ**

### CODE REVIEW

**Comment by Elchi3** [comment]
I like the warning and error types. Well done! This needs a new test to verify the http check, too, though.

**Comment by SebastianZ** [comment]
There you are!

Sebastian

**Comment by Elchi3** [comment]
This looks good to me but it needs a re-base now.

**Comment by SebastianZ** [comment]
Rebased and added unit test.

Sebastian

**Pull request merged**
