### PR TITLE
Added test for incorrectly set hightlighted line (issue #18)

### PR DESCRIPTION
**Pull request by SebastianZ**

### CODE REVIEW

**Comment by Elchi3** [comment]
- There is a warning with this code:

```
[JavaScript Warning: "SyntaxError: test for equality (==) mistyped as assignment (=)?"  {
  file: test/test-doctests.js" line: 129 column: 47 
  source: "while (match = reCodeSample.exec(content)) {"
}]
```
- There is still a console.log in this line: https://github.com/Elchi3/mdn-doc-tests/pull/38/files#diff-342b0a6752d724448b0e569b50989b43R130

**Comment by SebastianZ** [comment]
Thanks for the hint! Should be fixed now.

Sebastian

**Comment by Elchi3** [comment]
If this gets rebased, I can merge it. Looks good to me.

**Comment by SebastianZ** [comment]
Now rebased.

Sebastian

**Pull request merged**
