### PR TITLE
Issue 83: Test for URLs in link titles

### PR DESCRIPTION
**Pull request by SebastianZ**

### CODE REVIEW

**Comment by Elchi3** [comment]
I expect this to appear with old URLs (see the same named test).

Should we add these two tests, because of this assumption?
<a href="/en-US/docs/Web" title="/en/Web">Web</a>
<a href="/en-US/docs/Mozilla" title="/En/Mozilla">Mozilla</a>

**Comment by SebastianZ** [comment]
> Should we add these two tests, because of this assumption?
> <a href="/en-US/docs/Web" title="/en/Web">Web</a>
> <a href="/en-US/docs/Mozilla" title="/En/Mozilla">Mozilla</a>

Sure, I can add those.

Sebastian

**Comment by SebastianZ** [comment]
Added.

**Comment by Elchi3** [comment]
Thank you!

**Pull request merged**
