### PR TITLE
Issue 99: Highlight matches on hover

### PR DESCRIPTION
**Pull request by SebastianZ**

### CODE REVIEW

**Comment by Elchi3** [comment]
The hovering works well, though I wonder if the issue that was opened for this should have been: "Matches are indistinguishable". Hovering is one solution to solve this then. Another would be to add "even", "odd" styles, because the issue remains if there is no hover. However, I am happy to merge this as it improves the situation a bit.

**Comment by SebastianZ** [comment]
You're right, the issue is actually that matches are indistinguishable.
Three solutions:
- Don't merge, discuss the best solution and create a new patch.
- Merge and create a new issue to revisit this at a later point.
- Merge and forget.

I'm happy with every option. It's up to you.

Sebastian

**Comment by Elchi3** [comment]
I think I am choosing option 1, with the following:

I would propose to also add the "odd" and "even" styles, as it could improve the distinguish-ability when not hovering. I think that shouldn't be too hard to do, so how about doing that here?

**Comment by SebastianZ** [comment]
Ok. Another possible solution is to add borders between the matches.
I'll try both out and we can decide on what's better.

Sebastian

**Comment by Elchi3** [comment]
This needs a rebase, now that we have borders.

**Comment by SebastianZ** [comment]
> This needs a rebase, now that we have borders.

I thought the borders would be the replacement for the hover effect. Do you still want to add it?

Sebastian

**Comment by Elchi3** [comment]
I think the hover is quite subtle, so I have nothing against it. No strong feeling either way, though.

**Comment by SebastianZ** [comment]
Ok, let's keep it. It makes sense to have it for #49. I've rebased it now.

Sebastian

**Comment by SebastianZ** [comment]
Also a long night for you, hm? :last_quarter_moon_with_face: :-)

Thanks for merging!

Sebastian

**Pull request merged**
