### PR TITLE
Issue 67: Added error summary to the top of the results

### PR DESCRIPTION
**Pull request by SebastianZ**

### CODE REVIEW

**Comment by Elchi3** [comment]
This is cool!  It now needs a rebase.

I am wondering if we can increment the total count of warnings and errors, while running the tests. Currently there is another loop that collects the total number after the test run from the HTML or do I see that wrong?

**Comment by SebastianZ** [comment]
> I am wondering if we can increment the total count of warnings and errors, while running the tests. Currently there is another loop that collects the total number after the test run from the HTML or do I see that wrong?

You're right in both points. I've changed that in https://github.com/Elchi3/mdn-doc-tests/commit/41b6aa66dedb17c3e66c8633c7eca5a82670aa94.

Sebastian

**Comment by Elchi3** [comment]
There are now 18 commits in this PR, some of which belong to other PRs (for adding the French l10n or for absoluteURLsForInternalLinks). Did something go wrong when rebasing this? Normally I would just expect the commits regarding this issue, but rebased against the master codebase.

**Comment by SebastianZ** [comment]
I don't know what happened. I'll check that. Maybe I need to create a new PR.

Sebastian

**Comment by SebastianZ** [comment]
Looks like a new rebase worked.

Sebastian

**Comment by Elchi3** [comment]
This is awesome! I like it very much. Merging!

**Comment by SebastianZ** [comment]
Thank you! I like it, too! ;-)

Sebastian

**Pull request merged**
