### PR TITLE
Turned regex strings into literals (issue #28)

### PR DESCRIPTION
**Pull request by SebastianZ**

### CODE REVIEW

**Comment by Elchi3** [comment]
I have not tested this PR yet, but from looking at the code, we can now also remove calls like `new RegExp(testObj.regex, 'gi')` to not create a new RegExp as we already have one, right? Both in test-doctests.js and runtests.js.

**Comment by SebastianZ** [comment]
> I have not tested this PR yet, but from looking at the code, we can now also remove calls like new RegExp(testObj.regex, 'gi') to not create a new RegExp as we already have one, right? Both in test-doctests.js and runtests.js.

You're right. I'll do another commit and ping you then.

Sebastian

**Comment by SebastianZ** [comment]
There you go.

Sebastian

**Comment by Elchi3** [comment]
Beautiful :+1: Thanks!

**Pull request merged**
