### PR TITLE
Added test for macro syntax errors (issue #13)

### PR DESCRIPTION
**Pull request by SebastianZ**

### CODE REVIEW

**Comment by Elchi3** [comment]
Please add a new test to https://github.com/Elchi3/mdn-doc-tests/blob/master/test/test-doctests.js so that we can see which wrong macro syntaxes are caught.

**Comment by SebastianZ** [comment]
Sure, just give me a bit.

Sebastian

**Comment by SebastianZ** [comment]
I've added the test now.

Sebastian

**Comment by Elchi3** [comment]
I would say that these cases are common and it looks like they are not caught:
{{macro("param)}}
{{macro(param)}}
{{macro(param"))}}

These two are caught now:
{{macro("param")}
{{macro("param"}}

@teoli2003, can you think of other common macro syntax typos?

**Comment by SebastianZ** [comment]
@Elchi3 Covered the cases mentioned plus a few more, so now those errors are recognized:

```
macro("param)}}   // Missing closing double quote
macro(\'param)}}  // Missing closing single quote
macro(param)}}    // Missing quotes
macro(param")}}   // Missing opening double quote
macro(param\')}}  // Missing opening single quote
macro("param"))}} // Double closing parameter list bracket
macro("param")}   // Missing closing macro curly brace
macro("param"}}   // Missing closing parameter list bracket
macro(param"}}    // Missing opening double quote and missing closing parameter list bracket
macro(param"))}}  // Missing opening double quote and double closing parameter list bracket
```

Some more combinations can be seen in the unit test.

Sebastian

**Comment by Elchi3** [comment]
Well done, this is great! :+1: 
I think it would be good to put the comments in the test code, too. Then it is easier to spot what each lines tests.
Also, this needs a rebase now.

**Comment by SebastianZ** [comment]
> I think it would be good to put the comments in the test code, too. Then it is easier to spot what each lines tests.

Done in 7c5f9ba.
And its rebased now, too.

Sebastian

**Pull request merged**
